---
name: Package

on:
  push:
  workflow_dispatch:

jobs:
  # No build actually happens here.
  provenance:
      name: Generate artifact attestation
      uses: appdumpster/workflows/.github/workflows/sign-artifact.yml@main
      with:
        image-registry: quay.io
        image-repository: rbean/misleading
        image-digest: "sha256:6223d8cc2a50846c1ef00bbdedeb9a14e22b66c1f5d7438e7024085b134c40f6"
      secrets:
        image-registry-username: ${{ secrets.REGISTRY_USER }}
        image-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
