---
name: Package

on:
  push:
  workflow_dispatch:

jobs:
  # No build actually happens here.
  provenance:
      name: Generate artifact attestation
      uses: appdumpster/workflows/.github/workflows/sign-artifact.yml@main
      with:
        image-registry: quay.io
        image-repository: rbean/misleading
        image-digest: "sha256:a7882b107ea351fc294135c1e9b3be96d845dbd7874c90655fbb1351d38daf3b"
      secrets:
        image-registry-username: ${{ secrets.REGISTRY_USER }}
        image-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
